### PR TITLE
Update Rules: Points!

### PR DESCRIPTION
**Pull request by Lord0fPig5**
This is a terrible rule I shouldn’t have written this

### CODE REVIEW

**Review by douglie — CHANGES_REQUESTED** [review]
Nuh uh

**Comment by WhiteFurryPie** [comment]
This rule absolutely plagiarizes my own rule, rule #108, except adding the win required points.

**Review by WhiteFurryPie — CHANGES_REQUESTED** [review]
Think of an original idea, bozo

**Review by labria — APPROVED** [review]

**Review by douglie — CHANGES_REQUESTED** [review]
Thought that will do?

**Pull request closed without merging**
